### ISSUE TITLE
Question about toggle

### ISSUE THREAD

**Issue by MillingtonAllen** [jgabriel1/expo-sqlite-typeorm-article#3]
I'm curious about the file `src/data/repositories/TodosRepository.ts`

In the line `is_toggled = ((is_toggled | 1) - (is_toggled & 1))`,

`(is_toggled|1) ` should always evaluate to 1

`(is_toggled & 1)` should always evaluate to is_toggled

does `((is_toggled | 1) - (is_toggled & 1))` provide some type of boolean type safety?  Why is it preferred to `1 - is_toggled`?

**Comment by jgabriel1** [comment]
That's just a little trick to be able to toggle a boolean in SQLite. I'm not sure how it works internally with SQLite, but from what I remember that will always evaluate to the opposite, regardless of which state it's in.

It has something to do with the fact that SQLite does not have a boolean type and uses 0 or 1 instead.

**Comment by MillingtonAllen** [comment]
Looking at it more, my best guess is that the 1 in both `(is_toggled | 1)` and in `(is_toggled & 1)` was originally a bit mask.  It looks like it is derived from old C style code where they pack multiple booleans into one variable (for example, a char can hold 8 booleans since the char is 8 bytes).  is_toggled would be the char holding multiple related booleans.  

Something like:
```
char cloudy = b'100
char windy = b'010
char sunny = b'001

char weather = 000

function toggle_weather_condition(weather, bitmask) {
    return (weather | bitmask) - (weather & bitmask)

toggle_weather_condition(weather, cloudy);
```

At first glance, I wasn't sure if it was specific to an SQL implementation or booleans type safety, but that doesn't seem to be the case.  Looks like it was derived from old code and could be simplified further, though it is functionally correct as it stands.  Thanks.
